FortuneMon/Back

build.gradle, src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserRequestDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserResponseDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/FortuneMonApplication.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/ApiResponse.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/BaseCode.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/BaseErrorCode.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/ErrorReasonDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/ReasonDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/status/ErrorStatus.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/status/SuccessStatus.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/exception/ExceptionAdvice.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/exception/GeneralException.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/exception/handler/ExceptionHandler.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/exception/handler/TempHandler.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/RedisConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/SwaggerConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/security/JwtAuthenticationFilter.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/security/SecurityConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/controller/UserController.java, src/main/java/FortuneMonBackEnd/fortuneMon/domain/Pokemon.java, src/main/java/FortuneMonBackEnd/fortuneMon/domain/User.java, src/main/java/FortuneMonBackEnd/fortuneMon/jwt/JwtUtil.java, src/main/java/FortuneMonBackEnd/fortuneMon/repository/UserRepository.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/RefreshTokenService.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserService.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserServiceImpl.java
> #2
> JWT설정, 로그인 회원가입, CORS에러 해결, SWAGGER 설정변경.
=> Feat/#2 로그인, 회원가입 기능 구현

src/main/java/FortuneMonBackEnd/fortuneMon/domain/Routine.java, src/main/java/FortuneMonBackEnd/fortuneMon/domain/UserRoutine.java
> #7 
> routine entity 추가, user_routine - routine 단방향 manyToOne 연관관계 설정.
=> pr routine entity 추가 & 연관관계 매핑

src/main/java/FortuneMonBackEnd/fortuneMon/controller/UserPokemonController.java
유저 아이디를 받아서 전달한다다
> #1
> 유저 아이디를 파라미터로 주었음
> 
=> feat: #1 유저 포켓몬 기능 구현 완료

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserPokemonDTO.java
오타 수정
> #1
> 오타 수정
> userPokemonDTO에서 group -> groupName으로 수정
=> fix: #1 유저 포켓몬 기능 오타 수정

.github/workflows/main.yml, Dockerfile
=> pr Feat#21 cicd 구현

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/FortuneResponse.java, src/main/java/FortuneMonBackEnd/fortuneMon/controller/FortuneController.java, src/main/java/FortuneMonBackEnd/fortuneMon/repository/FortuneRepository.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneService.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneServiceImpl.java
오늘의 운세를 뽑고 볼과 운세를 저장한다
> #25 
> 오늘의 운세 뽑기 기능 구현
> 몬스터볼로 운세를 뽑고 볼을 저장한다. 뽑은 볼 기반으로 카테고리별 운세를 뽑아서 저장한다
=> feat: #25 운세 뽑기 기능 구현

src/main/java/FortuneMonBackEnd/fortuneMon/repository/FortuneRepository.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneServiceImpl.java
findAllByBallId -> findAllByMonsterBallId로 변경
> #29 
> 이름 에러 수정
> findAllByMonsterBallId로 수정
=> fix: #29 repository 이름 오류 수정

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/RoutineResponse.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/security/SecurityConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/RoutineServiceImpl.java
=> pr Fix/#35 전체 루틴 조회 응답 수정

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserRoutineInfoResponseDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserRoutineResponse.java, src/main/java/FortuneMonBackEnd/fortuneMon/repository/UserRoutineRepository.java
=> pr 유저의 진행중인 루틴 응답 수정(routineId추가)

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserResponseDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/apiPayload/code/status/ErrorStatus.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/WebConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/controller/UserController.java, src/main/java/FortuneMonBackEnd/fortuneMon/repository/UserPokemonRepository.java, src/main/java/FortuneMonBackEnd/fortuneMon/repository/UserRepository.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserService.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserServiceImpl.java
> #40 
> 아이디 , 닉네임 중복체크 구현, 유저정보 조회 api 구현(닉네임 ,파트너포켓몬정보)
=> pr Feature/#40 아이디 닉네임 중복체크 api 구현 유저정보 조회 api 구현

src/main/java/FortuneMonBackEnd/fortuneMon/controller/FortuneController.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneService.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneServiceImpl.java
카테고리 이름을 직접 지정하지 않고 요청을 받는 방식으로 수정
> #41 
> 운세 뽑기 시 카테고리 이름을 요청 받는 것으로 수정
> 클라이언트가 애정 건강 재물 카테고리를 전달하도록 수정하였음
=> fix: #41 category name error

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/CategoryRequest.java, src/main/java/FortuneMonBackEnd/fortuneMon/controller/FortuneController.java
파라미터를 받아오는 방식 수정
> #49
> 운세 파라미터 수정
> 파라미터를 RequestBody로 받아오는 것으로 수정
=> fix: #49 운세 뽑기 파라미터 수정정

src/main/java/FortuneMonBackEnd/fortuneMon/service/UserServiceImpl.java
> #53 
> 내정보 조회 응답 수정 - 예외처리 수정
> 파트너 포켓몬 없을 때, null로 출력되게 응답수정
=> pr 내정보 조회 응답 수정

src/main/java/FortuneMonBackEnd/fortuneMon/DTO/UserPokemonDTO.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserMonsterBallServiceImpl.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserPokemonServiceImpl.java
type을 문자열 list로 응답하도록 수정
> #59
> type 응답 내용 수정
> type 응답을 문자열 리스트로 수정, "," 기준으로 파싱하여 각각 리스트에 넣어 반환
=> fix: #59 포켓몬 타입 응답 형식 수정

src/main/java/FortuneMonBackEnd/fortuneMon/service/UserServiceImpl.java
> #67 
> 루틴 수행여부 체크 api 수정(해당 날짜에 RoutineLog가 없으면 새로 생성)
=> pr 루틴 수행여부 체크 api 수정

src/main/java/FortuneMonBackEnd/fortuneMon/controller/UserPokemonController.java, src/main/java/FortuneMonBackEnd/fortuneMon/service/UserPokemonServiceImpl.java
미보유 포켓몬 선택 시 에러 메시지 추가
> #70
> 파트너 포켓몬 기능 추가
> 미보유 포켓몬 선택 시 에러 메시지 출력
=> fix: #70 파트너 포켓몬 기능 추가

src/main/java/FortuneMonBackEnd/fortuneMon/config/security/SecurityConfig.java
=> pr swagger 권한설정

src/main/java/FortuneMonBackEnd/fortuneMon/config/WebConfig.java, src/main/java/FortuneMonBackEnd/fortuneMon/config/security/SecurityConfig.java
> #75 
> 프론트 앤드 배포 url 등록 (webconfig, securityconfig 파일 수정)
> cors 에러 해결
=> pr 프론트 앤드 배포 url 등록 (webconfig, securityconfig)

src/main/java/FortuneMonBackEnd/fortuneMon/controller/HealthCheckController.java
=> pr 서버 연결 check api구현

src/main/java/FortuneMonBackEnd/fortuneMon/controller/HealthCheckController.java
=> pr Feature/#77 서버 연결 확인 api 구현

src/main/java/FortuneMonBackEnd/fortuneMon/service/FortuneServiceImpl.java
루틴이 없으면 조언에 null 저장
> #82 
> 조언 응답 수정
> 루틴이 없으면 조언 null 저장
=> fix: #82 advice 수정
